// src/lib/activity/content/activity-5-1.ts
import type { ActivityContent } from "@/src/lib/activity/content-types";

export const activity51Content: ActivityContent = {
  slug: "activity-5-1",
  title: "Empowering Personal Commitment - Footprint Literacy & Habit Change",
  moduleLabel: "Module 5: Adult education for environmental sustainability",
  intro: "Empowering Personal Commitment - Footprint Literacy & Habit Change",
  meta: [
    { label: "Duration", value: "60 minutes (plus a 30-day pledge follow-up)", icon: "⏱" },
    { label: "Setting", value: "F2F", icon: "🧑‍🏫" },
    { label: "Type", value: "Lecture, Group activity", icon: "👥" },
  ],

  sections: [
    {
      id: "learning-focus",
      type: "cards",
      title: "Learning Focus",
      cards: [
        {
          title: "Topic",
          items: ["Adult education for environmental sustainability"],
        },
        {
          title: "Knowledge",
          items: [
            "Understand the principles of sustainability and environmental literacy, including energy, mobility, food systems, waste, and circular economy.",
            "Know the main frameworks and policy drivers of the green transition, especially the EU Green Deal, GreenComp, and green skills approaches promoted by Cedefop, UNESCO, and OECD.",
            "Understand the role of adult education in supporting transformative learning, behavioural change, civic participation, and access to green career pathways.",
            "Be aware of digital tools and community-based approaches that support sustainability learning and engagement.",
          ],
        },
        {
          title: "Skills",
          items: [
            "Design and facilitate active sustainability learning for adults using participatory and technology-enhanced methods.",
            "Translate environmental concepts into accessible learning materials and practical activities.",
            "Apply sustainability competence frameworks through systems thinking, critical thinking, collaboration, action competence, and reflection.",
            "Support learners in behaviour change, environmental self-assessment, community participation, and career development linked to the green transition.",
            "Monitor and evaluate the impact of learning activities on environmental awareness, behaviour, and civic engagement.",
          ],
        },
        {
          title: "Attitudes",
          items: [
            "Show commitment to inclusive, transformative, and action-oriented sustainability education.",
            "Demonstrate responsibility toward environmental stewardship, social fairness, and intergenerational equity.",
            "Promote lifelong learning, adaptability, innovation, and active participation in the green transition.",
            "Value collaboration, co-creation, and shared accountability in building sustainable futures.",
          ],
        },
      ],
    },

    {
      id: "requirements",
      type: "list",
      title: "Requirements",
      items: [
        "Projector and PC (for slides/online tools)",
        "Internet access (for footprint calculator or quiz)",
        "Smartphones or tablets (participants use for calculator/quizzes)",
        "Markers, sticky notes or paper (for writing pledges, mapping habit loops)",
      ],
    },

    {
      id: "steps",
      type: "steps",
      title: "Step-by-Step Activity",
      steps: [
        {
          title: "Phase 1: Introduction & Aims",
          duration: "0-10 minutes",
          body: [
            "Welcome participants and set a motivating tone. Start with a quick poll or question: “What is one habit you have that impacts the environment (good or bad)?” Have learners share in pairs or volunteers to create openness and relate to the topic.",
            "Introduce the session topic: Individual Commitment and Responsibility for sustainability. Explain that today’s workshop uses a TEAL approach - Technology-Enhanced Active Learning - meaning it will be interactive and tech-supported (e.g. using an online tool), not a passive lecture.",
            "Briefly outline the learning outcomes: by the end of the session, participants will (1) identify their top 3 personal impact areas (energy, food, mobility) and set a 30-day reduction target, (2) apply a cue-routine-reward plan to replace one unsustainable habit, and (3) track and interpret their behavior change using a log and before/after quizzes.",
            "Emphasize personal empowerment: “Small steps can lead to big impacts when it comes to sustainability.”",
            "Also note that this links to broader goals - personal changes matter immensely for the climate when supported by wider action, which we’ll tackle in the next submodule on community action.",
          ],
        },
        {
          title: "Phase 2: Personal Footprint Mini-Audit",
          duration: "10-20 minutes",
          body: [
            "Introduce the concept of a personal carbon/ecological footprint. Explain that individuals have different footprint “domains” - typically energy (home electricity, heating), food, and transportation are major ones.",
            "Using an online footprint calculator (e.g. [Ecological Footprint Calculator](https://www.footprintcalculator.org/) or similar tools), participants individually answer a short set of questions to estimate their own footprint or impact in key areas. This can be done via smartphones.",
            "Facilitator and assistants help anyone having trouble with the tech.",
            "After ~5 minutes, have participants jot down which 3 areas turned out to be their highest impact (e.g. “driving gasoline car,” “eating meat daily,” “home heating usage”).",
            "In pairs or small groups, they briefly discuss their reactions: Were any results surprising? Which area do they feel most able to change?",
            "Each participant then sets a 30-day reduction target for one or more of these areas - encourage SMART goals (Specific, Measurable, Achievable, Relevant, Time-bound).",
            "For instance: “Reduce car use by 30% by carpooling or biking twice a week,” or “Cut meat consumption from daily to 2x/week,” etc.",
            "They can write their personal targets on sticky notes.",
            "The facilitator can invite 2-3 people to share their targets, reinforcing positivity and realism.",
            "Highlight that focusing on these areas can significantly lower emissions - e.g. dietary and transport changes are among the most impactful personal climate actions.",
          ],
        },
        {
          title: "Phase 3: Habit Loop Redesign Activity",
          duration: "15-20 minutes",
          body: [
            "Transition to habit change as a key to meeting those targets. Give a mini-presentation (5 min) on the psychology of habits - introduce the habit loop (Cue - Routine - Reward), adapted from Charles Duhigg’s “The Power of Habit.”",
            "Define each component: a Cue triggers a behavior, the Routine is the behavior itself, and the Reward is the payoff that makes the brain want to repeat it.",
            "Illustrate with a simple example relevant to sustainability: e.g., Cue: getting home from work tired, Routine: turn on the TV and forget to turn off lights or AC, Reward: relaxation.",
            "Explain that to change an unsustainable habit, one strategy is to swap in a greener routine while keeping the cue and reward constant.",
            "Hand out or display a Habit Planner worksheet (cue–routine–reward template, e.g. printable habit tracker or planning sheet).",
            "Now ask participants to identify one unsustainable habit of their own that they want to change (ideally linked to the footprint areas above - for example, habitually using disposable plastics, driving short distances, leaving devices on standby, etc.).",
            "On the worksheet, they fill in their habit’s current Cue, Routine, Reward loop (for instance: Cue: feeling thirsty at work, Routine: buy a plastic water bottle, Reward: quenched thirst/convenience).",
            "Next, they brainstorm a replacement routine that is more sustainable but satisfies the same cue and reward (e.g. Routine: keep a reusable bottle at hand instead).",
            "Have participants pair up (or form small groups of 3) to share their habit and their proposed new routine, discussing if the new routine is realistic and what reward they can give themselves to reinforce it (the reward could be intrinsic, like feeling good about reducing waste, or small treats - as long as it doesn’t undermine the goal).",
            "Each pair can briefly report one example to the whole group, or the facilitator can spotlight a couple of well-thought-out habit changes.",
            "Emphasize the behavior change techniques: making cues for good habits obvious (e.g. leave the reusable bottle where you see it), and rewards satisfying.",
            "This planning exercise equips learners to actually implement a lifestyle change, addressing the outcome of applying a cue-routine-reward plan.",
            "It also models active learning - they’re applying concepts to their own life, which aligns with GreenComp’s emphasis on “embodying sustainability values” through personal responsibility.",
          ],
        },
        {
          title: "Phase 4: 30-Day Pledge & Accountability",
          duration: "10 minutes",
          body: [
            "Now it’s time to solidify commitment. Introduce the 30-Day Sustainability Pledge challenge: each participant will commit to a specific sustainable behavior change for the next month (this will typically relate to the habit they just redesigned or the footprint target they set).",
            "Distribute a simple pledge form or card.",
            "Give them a couple of minutes to write down their pledge in one sentence (e.g., “I pledge to [action] [frequency] for the next 30 days to reduce my [impact area].”).",
            "Encourage specificity: “I pledge to cycle to work at least 3 days a week instead of driving,” or “I pledge to take shorter 5-minute showers to save water/energy.”",
            "Once written, have participants pair up with an “accountability buddy” - ideally not the same person as before, to expand peer connections.",
            "In pairs, they exchange pledges: each reads their pledge to the other.",
            "Instruct them to discuss how they will hold each other accountable - for example, exchanging phone numbers or agreeing to send a weekly check-in message (“How’s it going with your pledge?”).",
            "If in an online setting, this can be done by pairing in breakout rooms and connecting via chat/email.",
            "The facilitator can optionally collect all pledges (or have everyone stick their pledge note on a “Commitment Wall” poster or virtual board) as a public display of commitment.",
            "Highlight that having a social accountability partner increases success in habit change, as they’ll motivate each other.",
            "This peer-support aspect leverages social learning and keeps the spirit of TEAL by potentially using tech (they might use messaging apps or an online group to log progress - a WhatsApp group or a shared Google Sheet for everyone’s check-ins, for example).",
            "Mention that this pledge aligns with broader movements - e.g., the UN’s ActNowcampaign encourages individual pledges on energy, transport, food, etc., demonstrating how personal lifestyle changes contribute to global goals.",
          ],
        },
        {
          title: "Phase 5: Wrap-up Discussion & Next Steps",
          duration: "10 minutes",
          body: [
            "Gather the whole group for reflection.",
            "Facilitate a short discussion: “What do you anticipate will be the biggest challenge in keeping your sustainable habit for 30 days?” and “What are you looking forward to or already finding rewarding in this change?” Let a few participants share their thoughts.",
            "This prepares them to be mindful of barriers (like convenience, cost, forgetfulness) and think of solutions (like setting phone reminders - a quick tech tip you can suggest - or placing visual cues).",
            "Acknowledge any common challenges mentioned, and invite the group to suggest tips to each other (crowdsource solutions, e.g., if someone worries about forgetting their new routine, others might suggest using a habit-tracker app or placing notes in strategic spots).",
            "Reiterate key takeaways of the session: by identifying their personal high-impact areas and committing to specific changes, they are practicing active sustainability.",
            "Stress that personal commitment and habit change are crucial competencies in sustainability - they reflect responsibility and self-efficacy, which are part of the values promoted by frameworks like GreenComp (the EU Sustainability Competence framework highlights values-driven action and personal responsibility).",
            "Importantly, mention that while individual actions alone won’t solve everything, they do matter: for instance, new research shows if widely adopted, lifestyle changes could theoretically cut global emissions significantly - and even if in practice we only achieve a fraction of that, every bit counts when added up.",
            "Moreover, individual changes can inspire others and build momentum for community-level change.",
          ],
        },
      ],
    },

    {
      id: "pledge",
      type: "text",
      title: "30-DAY SUSTAINABILITY PLEDGE",
      body: [
        "Name: _________________________   Date: __________",
        "",
        "My 30-day pledge (one clear, measurable action):",
        "",
        "“I pledge to ___________________________________________________________ for the next 30 days to reduce my impact on __________________.”",
        "",
        "Impact area (tick one): [ ] Energy  [ ] Food  [ ] Mobility  [ ] Waste  [ ] Other: __________",
        "",
        "Start date: __________  End date: __________",
        "",
        "Accountability buddy: _________________________  Contact: _________________________",
        "",
        "Check-in plan (when/how): ______________________________________________________",
        "",
        "Public commitment posted:  [ ] Wall  [ ] Online board / Link: _______________________",
        "",
        "Weekly check-ins:",
        "",
        "Week 1  [ ] done   Notes: ______________________________________________",
        "",
        "Week 2  [ ] done   Notes: ______________________________________________",
        "",
        "Week 3  [ ] done   Notes: ______________________________________________",
        "",
        "Week 4  [ ] done   Notes: ______________________________________________",
        "",
        "Evidence (photo/link/brief proof): _______________________________________________",
        "",
        "End-of-challenge reflection (1-2 lines):",
        "",
        "Key insight/benefit: ____________________________________________________________",
        "",
        "Next action I will continue: _____________________________________________________",
        "[Download the 30-Day Sustainability Pledge (PDF)](https://pjjslpdbnwfkvlrxrkpr.supabase.co/storage/v1/object/public/course-assets/dsd-teal/Module-5/Activity-5-1/activity-5-1-pledge.pdf)",
      ],
    },

    {
      id: "assessment",
      type: "text",
      title: "Assessment",
      body: [
        "Assessment: Assessment in this activity is largely formative and based on participation and self-reflection.",
        "During the session, observe each participant’s engagement: Did they identify their high-impact areas accurately and set a concrete reduction goal? (Circulate during the footprint mini-audit to help interpret results.) Were they able to articulate a habit loop and propose a realistic new routine in the planner? Listen during pair discussions and have a few share-outs - this provides insight into their understanding of habit change concepts.",
        "The quality of pledges is another indicator: a clear, specific pledge suggests they grasp goal-setting.",
        "As an immediate check, you might do a quick show of hands: “How many feel confident they can keep this up for 30 days?” - if few hands, it signals need to reinforce motivation or adjust difficulty.",
        "The “before & after” quiz mentioned in outcomes will serve to assess knowledge gains and attitude change: for example, at the very start you could have given a short quiz or poll on sustainability knowledge or personal behavior frequency. That same quiz can be given after 30 days (either in a follow-up session or via an online form) to see what changed - e.g., an increase in correct answers or in self-reported sustainable actions.",
        "Throughout the 30 days, the pledge log itself is a tool for self-assessment: participants track each day they fulfill the habit (or track metrics like kWh saved, km not driven, etc.), and this log can be reviewed at the end.",
        "As a facilitator, you can collect these logs or ask participants to report back one highlight and one challenge from their experience.",
        "Success is indicated by reflections such as “I didn’t miss driving on Wednesdays and saved fuel” or “I’m now very aware of my meat intake and cut it in half.” Even challenges (e.g., “Week 2 was hard”) are learning opportunities to discuss.",
        "Finally, the accountability buddy check-ins serve as a peer-assessment mechanism - buddies can encourage and gently hold each other accountable, and you might ask each pair to briefly summarize their partner’s progress after 30 days.",
        "The combination of quiz results, pledge logs, and shared experiences will demonstrate achievement of the learning outcomes: they will have concrete data on reduction in their footprint area, a lived experience of habit change, and personal insights from tracking their journey.",
      ],
    },
    {
      id: "further-reading",
      type: "links",
      title: "Further Reading",
      items: [
        {
          title: "TEAL Methodology - MIT Case Study: “Educational Transformation through Technology at MIT - TEAL.”",
          url: "https://web.mit.edu/edtech/casestudies/teal.html",
          resourceType: "external",
        },
        {
          title: "Carbon Literacy Project - Carbon Literacy for Individuals",
          url: "https://carbonliteracy.com/individual/",
          resourceType: "external",
        },
      ],
    },
  ],
};
